Repository AY2021S1-CS2103T-F13-3/tp, pull requests merged in 2020-11, with the labels that each got.

#215 Fix MCR validation bug
  src/main/java/seedu/medibook/model/doctor/Mcr.java
  src/test/java/seedu/medibook/model/doctor/McrTest.java
Labels: type.Bug

#214 Update phone number restriction
  docs/UserGuide.md
  src/main/java/seedu/medibook/model/patient/Phone.java
  src/test/java/seedu/medibook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/medibook/model/patient/FieldContainsKeywordsPredicateTest.java
  src/test/java/seedu/medibook/model/patient/PhoneTest.java
Labels: type.Bug, type.Documentation

#213 Change EditCommand to update both height and weight when either one is edited
  src/main/java/seedu/medibook/logic/commands/EditCommand.java
Labels: type.Enhancement

#216 Add prestontyr.md
  docs/team/prestontyr.md
Labels: type.Documentation

#224 Fix findCommand context bug
  src/main/java/seedu/medibook/logic/commands/FindCommand.java
Labels: type.Bug

#226 Update prestontyr.md
  docs/team/prestontyr.md
Labels: type.Documentation

#227 Add junhao's PPP
  docs/team/wang-jun-hao.md
Labels: type.Documentation

#228 Update PPP link in about us
  docs/AboutUs.md
Labels: type.Documentation

#231 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AccessCommandSequenceDiagram.puml
  docs/diagrams/CreateAccountSequenceDiagram.puml
  docs/diagrams/LoginSequenceDiagram.puml
  docs/images/AccessCommandSequenceDiagram.png
  docs/images/CreateAccountSequenceDiagram.png
  docs/images/LoginSequenceDiagram.png
Labels: type.Documentation

#232 Update Preston's PPP
  docs/AboutUs.md
  docs/team/prestontyr.md
Labels: type.Documentation

#235 Update DG for charts in Patient Profile
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/screenshots/addNote.PNG
  docs/images/screenshots/chartScreenShot.PNG
  docs/images/screenshots/createAccount.PNG
  docs/images/screenshots/deleteCmd.PNG
  docs/images/screenshots/deleteNote.PNG
  docs/images/screenshots/editNote.PNG
  docs/images/screenshots/helpCmd.PNG
Labels: type.Documentation

#233 Add zheng zhi's PPP
  docs/team/wong-zz.md
Labels: type.Documentation

#243 Fix PPP format
  docs/team/divakarmal.md
  docs/team/prestontyr.md
Labels: type.Documentation

#238 Branch update dg for v1.4
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PatientProfileClassDiagram.puml
  docs/diagrams/PatientProfileSequenceDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/PatientProfileClassDiagram.png
  docs/images/PatientProfileSequenceDiagram.png
Labels: type.Documentation

#236 Branch add ppp
  docs/AboutUs.md
  docs/team/foojingyi.md
Labels: type.Documentation

#237 Branch change icon
  src/main/java/seedu/medibook/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/icon.png
  src/main/resources/images/placeholder.png
  src/main/resources/view/CreateAccountWindow.fxml
  src/main/resources/view/LoginWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/medibook/commons/util/AppUtilTest.java
Labels: type.Enhancement

#240 Branch update readme
  README.md
Labels: type.Documentation

#242 Update login and create account features in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#244 Update logout method so that context is reset
  src/main/java/seedu/medibook/logic/LogicManager.java
Labels: type.Bug

#249 Fix DG headers
  docs/DeveloperGuide.md
Labels: type.Documentation

#253 Add page breaks
  docs/team/prestontyr.md
Labels: type.Documentation

#252 Update UG examples to match SS
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#255 Add user stories and use cases to DG
  docs/DeveloperGuide.md
  docs/team/wong-zz.md
Labels: type.Documentation
