Repository AY2021S1-CS2103T-F13-3/tp, pull requests merged in 2020-10, with the labels that each got.

#26 Add Weight field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Weight.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/WeightTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#27 Fix weight test bugs in NameContainsKeywordPredicateTest
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: bug, severity.VeryLow, type.Bug

#28 Update DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#29 Update homepage for project website
  docs/index.md
Labels: documentation

#24 Update project website
  README.md
  docs/AboutUs.md
  docs/images/Ui.png
Labels: documentation, priority.High

#41 Update ParserUtil.java javadoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: documentation

#40 Update test function in UniquePersonListTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: severity.VeryLow

#43 Update _config.yml file to remove traces of AB-3
  docs/_config.yml
Labels: documentation, priority.High

#42 Add date of birth field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/DateOfBirthTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#73 Add MedicalNoteList, hook MedicalNote class into program
  src/main/java/seedu/medibook/logic/Logic.java
  src/main/java/seedu/medibook/logic/LogicManager.java
  src/main/java/seedu/medibook/logic/commands/AddCommand.java
  src/main/java/seedu/medibook/logic/commands/EditCommand.java
  src/main/java/seedu/medibook/logic/commands/FindCommand.java
  src/main/java/seedu/medibook/logic/commands/NoteCommand.java
  src/main/java/seedu/medibook/logic/parser/AddCommandParser.java
  src/main/java/seedu/medibook/logic/parser/CliSyntax.java
  src/main/java/seedu/medibook/logic/parser/EditCommandParser.java
  src/main/java/seedu/medibook/logic/parser/FindCommandParser.java
  src/main/java/seedu/medibook/logic/parser/MediBookParser.java
  src/main/java/seedu/medibook/logic/parser/NoteCommandParser.java
  src/main/java/seedu/medibook/logic/parser/ParserUtil.java
  src/main/java/seedu/medibook/model/Date.java
  src/main/java/seedu/medibook/model/Model.java
  src/main/java/seedu/medibook/model/ModelManager.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNote.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNoteList.java
  src/main/java/seedu/medibook/model/patient/DateOfBirth.java
  src/main/java/seedu/medibook/model/patient/FieldContainsKeywordsPredicate.java
  src/main/java/seedu/medibook/model/patient/Patient.java
  src/main/java/seedu/medibook/storage/JsonAdaptedPatient.java
  src/main/java/seedu/medibook/ui/MainWindow.java
  src/main/java/seedu/medibook/ui/PatientCard.java
  src/test/java/seedu/medibook/logic/commands/AddCommandTest.java
  src/test/java/seedu/medibook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/medibook/logic/commands/FindCommandTest.java
  src/test/java/seedu/medibook/logic/commands/NoteCommandTest.java
  src/test/java/seedu/medibook/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/medibook/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/medibook/model/medicalnote/MedicalNoteTest.java
  src/test/java/seedu/medibook/model/patient/FieldContainsKeywordsPredicateTest.java
  src/test/java/seedu/medibook/testutil/PatientUtil.java
Labels: type.Enhancement

#75 Implement storage for MedicalNoteList
  src/main/java/seedu/medibook/MainApp.java
  src/main/java/seedu/medibook/logic/LogicManager.java
  src/main/java/seedu/medibook/logic/commands/AccessCommand.java
  src/main/java/seedu/medibook/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/medibook/model/UserPrefs.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNote.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNoteList.java
  src/main/java/seedu/medibook/model/medicalnote/ReadOnlyMedicalNoteList.java
  src/main/java/seedu/medibook/model/patient/Patient.java
  src/main/java/seedu/medibook/storage/JsonAdaptedMedicalNote.java
  src/main/java/seedu/medibook/storage/JsonMediBookStorage.java
  src/main/java/seedu/medibook/storage/JsonMedicalNoteListStorage.java
  src/main/java/seedu/medibook/storage/JsonSerializableMedicalNoteList.java
  src/main/java/seedu/medibook/storage/MedicalNoteListStorage.java
  src/main/java/seedu/medibook/storage/Storage.java
  src/main/java/seedu/medibook/storage/StorageManager.java
  src/test/data/JsonMedicalNoteListStorageTest/invalidAndValidPatientMedicalNotes/medicalnotes/S7329204G.json
  src/test/data/JsonMedicalNoteListStorageTest/invalidPatientMedicalNotes/medicalnotes/S7329204G.json
  src/test/data/JsonMedicalNoteListStorageTest/notJsonFormatMedicalNotes/medicalnotes/S7329204G.json
  src/test/data/JsonSerializableMedicalNoteListTest/invalidPatientMedicalNotes.json
  src/test/data/JsonSerializableMedicalNoteListTest/typicalPatientMedicalNotes.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/medibook/logic/LogicManagerTest.java
  src/test/java/seedu/medibook/model/UserPrefsTest.java
  src/test/java/seedu/medibook/storage/JsonAdaptedMedicalNoteTest.java
  src/test/java/seedu/medibook/storage/JsonMedicalNoteListStorageTest.java
  src/test/java/seedu/medibook/storage/JsonSerializableMedicalNoteListTest.java
  src/test/java/seedu/medibook/storage/StorageManagerTest.java
  src/test/java/seedu/medibook/testutil/TypicalMedicalNotes.java
Labels: type.Task

#79 Modify JsonAdaptedMedicalNote toModelType to make use of existing checks
  src/main/java/seedu/medibook/storage/JsonAdaptedMedicalNote.java
  src/test/java/seedu/medibook/storage/JsonAdaptedMedicalNoteTest.java
Labels: priority.Low

#83 change font size
  src/main/resources/view/TableView.css
Labels: type.Task

#82 Add unit tests, handle exception and remove debugging code
  src/main/java/seedu/medibook/logic/commands/NoteCommand.java
  src/main/java/seedu/medibook/logic/parser/NoteCommandParser.java
  src/main/java/seedu/medibook/model/Date.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNoteList.java
  src/test/java/seedu/medibook/logic/commands/NoteCommandTest.java
  src/test/java/seedu/medibook/model/DateTest.java
  src/test/java/seedu/medibook/model/medicalnote/MedicalNoteListTest.java
  src/test/java/seedu/medibook/model/patient/DateOfBirthTest.java
Labels: type.Task

#103 Update DG for optional fields and login functionality
  docs/DeveloperGuide.md
  docs/diagrams/CreateAccountActivityDiagram.puml
  docs/diagrams/CreateAccountSequenceDiagram.puml
  docs/diagrams/LoginSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/CreateAccountActivityDiagram.png
  docs/images/CreateAccountSequenceDiagram.png
  docs/images/LoginSequenceDiagram.png
  docs/images/ModelClassDiagramUpdated.png
Labels: type.Documentation

#111 Update DG to include implementation details on Note Command
  docs/DeveloperGuide.md
  docs/diagrams/NoteSequenceDiagramFocusLogic.puml
  docs/diagrams/NoteSequenceDiagramSDUpdatePatientInModel.puml
  docs/images/NoteSequenceDiagramFocusLogic.png
  docs/images/NoteSequenceDiagramSDUpdatePatientInModel.png
Labels: type.Documentation

#104 Update UG to include 'note' command
  docs/UserGuide.md
Labels: type.Documentation

#115 Update format of delete command and order of features in UG
  docs/UserGuide.md
Labels: type.Documentation

#112 Update DG with changes made for enhanced FindCommand
  docs/DeveloperGuide.md
  docs/diagrams/FindClassDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/FindClassDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Documentation

#116 Remove guiding note boxes and change format of delete command usage in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#123 Update UI component in DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Documentation

#121 Add elaboration on example in UG for edit command
  docs/UserGuide.md
Labels: type.Documentation

#122 Update design consideration elaboration
  docs/DeveloperGuide.md
Labels: type.Documentation

#125 Add more details for note command in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#127 Update version number to v1.2.1 in MainApp.java
  src/main/java/seedu/medibook/MainApp.java
Labels: type.Documentation

#128 Branch update ug
  docs/UserGuide.md
Labels: type.Documentation

#126 Branch update dg
  UiClassDiagram.png
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: type.Documentation

#129 Branch update dg
  UiClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Documentation

#97 Integrate medical notes storage with EditCommand, DeleteCommand and ClearCommand
  docs/tutorials/AddRemark.md
  src/main/java/seedu/medibook/commons/util/FileUtil.java
  src/main/java/seedu/medibook/logic/LogicManager.java
  src/main/java/seedu/medibook/logic/commands/AccessCommand.java
  src/main/java/seedu/medibook/logic/commands/ClearCommand.java
  src/main/java/seedu/medibook/logic/commands/DeleteCommand.java
  src/main/java/seedu/medibook/logic/commands/EditCommand.java
  src/main/java/seedu/medibook/logic/commands/NoteCommand.java
  src/main/java/seedu/medibook/model/Context.java
  src/main/java/seedu/medibook/model/Model.java
  src/main/java/seedu/medibook/model/ModelContext.java
  src/main/java/seedu/medibook/model/ModelManager.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNoteList.java
  src/main/java/seedu/medibook/storage/JsonMedicalNoteListStorage.java
  src/main/java/seedu/medibook/storage/MedicalNoteListStorage.java
  src/main/java/seedu/medibook/storage/StorageManager.java
  src/test/data/JsonMedicalNoteListStorageTest/emptyMedicalNotes/medicalnotes/S7329204G.json
  src/test/java/seedu/medibook/logic/commands/AddCommandTest.java
  src/test/java/seedu/medibook/logic/commands/ClearCommandTest.java
  src/test/java/seedu/medibook/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/medibook/logic/commands/EditCommandTest.java
  src/test/java/seedu/medibook/logic/commands/NoteCommandTest.java
  src/test/java/seedu/medibook/model/ModelContextTest.java
  src/test/java/seedu/medibook/storage/JsonMedicalNoteListStorageTest.java
  src/test/java/seedu/medibook/storage/StorageManagerTest.java
Labels: priority.Medium, type.Task

#136 Implement sorting of medical notes by date of creation (Order: 1)
  src/main/java/seedu/medibook/logic/commands/NoteCommand.java
  src/main/java/seedu/medibook/model/Date.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNote.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNoteComparator.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNoteList.java
  src/test/java/seedu/medibook/model/DateTest.java
  src/test/java/seedu/medibook/model/medicalnote/MedicalNoteComparatorTest.java
  src/test/java/seedu/medibook/model/medicalnote/MedicalNoteListTest.java
Labels: type.Enhancement

#140 Implement check for duplicate notes in medical note list (Order: 3)
  src/main/java/seedu/medibook/logic/commands/AddNoteCommand.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNoteList.java
  src/main/java/seedu/medibook/model/patient/Patient.java
  src/test/java/seedu/medibook/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/medibook/model/medicalnote/MedicalNoteListTest.java
  src/test/java/seedu/medibook/model/patient/PatientTest.java
  src/test/java/seedu/medibook/testutil/PatientBuilder.java
  src/test/java/seedu/medibook/testutil/TypicalPatients.java
Labels: type.Enhancement

#102 Create new Record class to store the past records of a patient's Height and Weight
  src/main/java/seedu/medibook/logic/commands/EditCommand.java
  src/main/java/seedu/medibook/logic/parser/AddCommandParser.java
  src/main/java/seedu/medibook/model/patient/Patient.java
  src/main/java/seedu/medibook/model/patient/Record.java
  src/main/java/seedu/medibook/model/util/SampleDataUtil.java
  src/main/java/seedu/medibook/storage/JsonAdaptedPatient.java
  src/main/java/seedu/medibook/storage/JsonAdaptedRecord.java
  src/test/data/JsonSerializableMediBookTest/duplicatePatientMediBook.json
  src/test/data/JsonSerializableMediBookTest/typicalPatientMediBook.json
  src/test/java/seedu/medibook/model/patient/RecordTest.java
  src/test/java/seedu/medibook/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/medibook/storage/JsonAdaptedRecordTest.java
Labels: priority.Medium, type.Enhancement

#149 Fix bug caused by loading of medical notes with invalid format.
  src/main/java/seedu/medibook/storage/StorageManager.java
Labels: severity.Medium, type.Bug

#150 Fix ic input only accepting upper case
  src/main/java/seedu/medibook/model/patient/Ic.java
Labels: severity.Low, type.Bug

#155 Add javadoc for more classes and public methods
  src/main/java/seedu/medibook/logic/commands/AddNoteCommand.java
  src/main/java/seedu/medibook/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/medibook/logic/parser/DeleteNoteCommandParser.java
  src/main/java/seedu/medibook/logic/parser/EditNoteCommandParser.java
  src/main/java/seedu/medibook/model/commonfields/Date.java
  src/main/java/seedu/medibook/model/commonfields/Name.java
  src/main/java/seedu/medibook/model/doctor/Doctor.java
  src/main/java/seedu/medibook/model/doctor/Mcr.java
  src/main/java/seedu/medibook/model/medicalnote/Content.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNote.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNoteComparator.java
  src/main/java/seedu/medibook/model/medicalnote/MedicalNoteList.java
  src/test/java/seedu/medibook/logic/commands/EditNoteCommandTest.java
  src/test/java/seedu/medibook/model/medicalnote/MedicalNoteComparatorTest.java
  src/test/java/seedu/medibook/model/medicalnote/MedicalNoteListTest.java
Labels: type.Documentation

#154 Update UG to include addnote, editnote and deletenote features
  docs/UserGuide.md
Labels: type.Documentation

#170 Update userguide
  docs/UserGuide.md
Labels: type.Documentation

#174 Update UG
  docs/UserGuide.md
Labels: type.Documentation
